# Per-project orch config (.orch.yml)
# Place this file in your project root directory.
# Values here override the global config (~/.orch/config.yml).
#
# Only include the keys you want to override — everything else
# falls through to the global config.

# Required — identifies this project on GitHub
gh:
  repo: "myorg/myproject"
#   project_id: "PVT_..."
#   project_status_field_id: ""
#   project_status_map:
#     backlog: ""
#     in_progress: ""
#     review: ""
#     done: ""

# Tools that must be available on PATH before an agent is launched.
# If any are missing, the task is blocked immediately with a clear reason.
#
# required_tools:
#   - bun
#   - anchor
#   - solana-test-validator

# workflow:
#   auto_close: false
#   review_owner: "@myhandle"
#   enable_review_agent: true
#   auto_create_followup_on_changes: true
#   auto_close_task_on_approval: false

# router:
#   agent: "claude"
#   model: "haiku"
#   fallback_executor: "codex"

# Scheduled jobs for this project
# jobs:
#   - id: daily-sync
#     schedule: "0 9 * * *"         # cron expression (min hour dom month dow)
#     task:
#       title: "Daily code sync"
#       body: "Pull latest changes and run linting"
#       labels: [sync]
#       agent: ""                   # empty = let router decide
#     enabled: true
#
# Schedule shortcuts: @hourly @daily @weekly @monthly @yearly
#
# Dedup: if active_task_id points to a task that isn't "done",
# the job waits. Tasks can delegate, retry, get reviewed — the
# job won't create a duplicate until the previous run finishes.
