project_dir: "/Users/gb/Projects/orch"
gh:
  repo: "gabrielkoerich/orch"

# Schedule shortcuts: @hourly @daily @weekly @monthly @yearly
jobs:
  - id: code-review-orch
    type: task
    schedule: 0 4,17 * * *
    task:
      title: 'Code review: orch'
      body: |
        Review the orch codebase (src/**/*.rs, scripts/*.sh, prompts/*.md, justfile, Formula). Look for: bugs, dead code, missing error handling, performance issues, code duplication, inconsistencies, outdated comments.

        Suggest concrete improvements with file paths and line numbers. Check test coverage gaps. Do NOT make changes — only report findings.

        Create github issues for each issue found, following these guidelines:

        When creating issues:
        - ALWAYS trace symptoms to their root cause. Create ONE task for the root cause, not one per symptom.
        - Check existing open issues first (`gh issue list --state open`). Do not create duplicates.
        - Maximum 2-3 high-quality tasks. Fewer is better. Each must be actionable with a clear fix.
        - Do not create cleanup/janitorial tasks — just do the cleanup yourself or flag it in the summary.
        - Do not create issues for edge cases or workarounds. Fix root causes only.

        Prioritize fixes that improve reliability and agent success rate.
      labels:
        - review
        - self-improvement
      agent: null
    command: null
    dir: /Users/gb/Projects/orch
    enabled: true
    last_run: "2026-02-25T17:01:27Z"
    last_task_status: done
    active_task_id: ""
  - id: code-development-orch
    type: task
    schedule: 0 2,15 * * *
    task:
      title: 'Code development: orch'
      body: |
        Review the PLAN.md file. Look for: what still needs to be implemented and what is already implemented. This is a new version of the orchestrator and were're rewriting the core into Rust.

        Suggest concrete improvements with file paths and line numbers. Follow the PLAN.

        Create github issues for each new feature or change in the plan, following these guidelines:

        When creating github issues:
        - Check existing open issues first (`gh issue list --state open`). Do not create duplicates.
        - ALWAYS THINK about the architecture first. Do not create tasks that overlaps.
        - Think about interfaces and implementations. Channels and connections.
        - ALWAYS trace symptoms to their root cause. Create ONE task for the root cause, not one per symptom.
        - Maximum 2-3 high-quality tasks. Fewer is better. Each must be actionable with a clear improvement.
        - Do not create tasks for edge cases or workarounds. Improvement or real features only.
        - Do not forget to tell the agents to update the docs.
        - Do not forget to tell the agents to update the PLAN.md with the things that are already implemented, make a TODO list if doesn't exist.

        Prioritize improvements that makes the development agile.
      labels:
        - review
        - self-improvement
      agent: null
    command: null
    dir: /Users/gb/Projects/orch
    enabled: true
    last_run: "2026-02-25T18:00:23Z"
    last_task_status: done
    active_task_id: ""
